/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xalanq_vpn4over6_MainActivity */

#ifndef _Included_com_xalanq_vpn4over6_MainActivity
#define _Included_com_xalanq_vpn4over6_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
