/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xalanq_vpn4over6_Backend */

#ifndef _Included_com_xalanq_vpn4over6_Backend
#define _Included_com_xalanq_vpn4over6_Backend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xalanq_vpn4over6_Backend
 * Method:    serve
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_xalanq_vpn4over6_Backend_serve
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_xalanq_vpn4over6_Backend
 * Method:    connectLocalSocket
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xalanq_vpn4over6_Backend_connectLocalSocket
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_xalanq_vpn4over6_Backend
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xalanq_vpn4over6_Backend_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
